---
- name: Deploy and configure Zabbix Agent
  hosts: labrat
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisites
      package:
        name:
          - wget
          - gnupg
        state: present

    - name: Download Zabbix repository package
      get_url:
        url: "{{ zabbix_repo_url }}/{{ zabbix_repo_package }}"
        dest: /tmp/{{ zabbix_repo_package }}
        mode: '0644'

    - name: Install Zabbix repository
      ansible.builtin.apt:
        deb: /tmp/{{ zabbix_repo_package }}

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Zabbix Agent
      package:
        name:
          - zabbix-agent2
        state: present

    - name: Create zabbix agent configuration directory
      file:
        path: /etc/zabbix/zabbix_agent2.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure Zabbix Agent
      template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.d/zabbix_agent2.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart zabbix-agent2

    - name: Ensure Zabbix Agent is enabled and started
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Check Zabbix Agent status
      command: systemctl is-active zabbix-agent2
      register: zabbix_status
      changed_when: false

    - name: Show Zabbix Agent status
      debug:
        msg: "Zabbix Agent is {{ zabbix_status.stdout }} on {{ inventory_hostname }}"

  handlers:
    - name: restart zabbix-agent2
      systemd:
        name: zabbix-agent2
        state: restarted
