---
- hosts: nucs
  become: true
  tasks:
    - name: Remove already existed download
      ansible.builtin.shell: rm -f /home/semaphore/inbody.exe
      
    - name: Download latest binary
      ansible.builtin.get_url:
        url: https://storage.yandexcloud.net/ddx-mobile-app/last-releast/inbody.exe
        dest: /home/semaphore/inbody.exe
        mode: '0777'
        force: yes

    - name: Stop inbody service
      ansible.builtin.service:
        name: inbody
        state: stopped

    - name: move new binary
      ansible.builtin.command: mv /home/semaphore/inbody.exe /opt/inbody/inbody.exe

    - name: Start inbody service
      ansible.builtin.service:
        name: inbody
        state: started
